#! /bin/bash
#Syntax synthdatagen srcdirectory version

generateSynthFile() {
	filename=$(basename $1)

	lbzcat $1 | sed "s/\(<.*> <.*\)\(> .* \.\)/\1$date\2/" | bzip2 > $2/$filename
}

date=$(date +%Y.%m.%d)
generic_artifacts="disambiguations homepages"
mapping_artifacts="specific_mappingbased_properties geo_coordinates_mappingbased"
content_variants="enwiki dewiki"

for artifact in $1/*; do
	if ! [ -d $artifact/$date/ ]
	then
		mkdir $artifact/$date/
	fi
	for file in $artifact/$2/*.ttl.bz2; do
		generateSynthFile $file $artifact/$date
	done
done

